#include <iostream>
#include <vector>
#include <cmath>
#include <iomanip>
#include <string_view>
#include <arrayfire.h>
#include <iterator>
#include <cstddef>
#include <unordered_set>
#include <type_traits>
#include <random>
#include <chrono>
#include <thread>
#include <algorithm>
#include <functional>
#include <typeinfo>
#include <span>
#include <ctime>
#include <unordered_map>
#include <unordered_set>
#include <memory>
