#pragma once
#include "Perceptron.h"
#include "Layering.h"
#include "ActivationFunction.h"
#include "PerceptronFeedForward.h"
#include "BackPropagation.h"
// #include "Headers/Optimizer/GradientDescent.h"
// #include "Headers/Optimizer/StochasticGradientDescentWithMomentum.h"
// #include "Headers/Optimizer/AdaptiveGradientDescent.h"
// #include "Headers/Optimizer/RootMeanSquaredPropagation.h"
// #include "Headers/Optimizer/AdaptiveMomentEstimation.h"
