name: CI for Lantern Project with ArrayFire on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install wget
        run: |
          choco install wget

      - name: Install VCPKG
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          dir
          cd vcpkg && bootstrap-vcpkg.bat
        working-directory: ${{ github.workspace }}
          
      - name: Get and install arrayfire
        shell: cmd
        run: |
          set VCPKG_ROOT=${{ github.workspace }}\vcpkg
          set PATH=%VCPKG_ROOT%;%PATH%
          wget https://github.com/arrayfire/arrayfire/archive/refs/tags/v3.9.0.zip
          tar -xf v3.9.0.zip
          cd v3.9.0/arrayfire-3.9.0
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        working-directory: ${{ github.workspace }}
