name: CI for Lantern Project with ArrayFire on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install wget
        run: |
          choco install wget vcpkg --y
          
      - name: Get and install arrayfire
        shell: cmd
        run: |
          wget https://github.com/arrayfire/arrayfire/archive/refs/tags/v3.9.0.zip
          tar -xf v3.9.0.zip
          cd v3.9.0/arrayfire-3.9.0
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/ProgramData/chocolatey/lib/vcpkg/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
        working-directory: ${{ github.workspace }}
