name: CMake with MSVC
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup and build
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg && bootstrap-vcpkg.bat
        cd ..
        set PATH=${{ github.workspace }}\vcpkg;%PATH%
        set VCPKG_ROOT=${{ github.workspace }}\vcpkg
        vcpkg integrate install
        vcpkg install --triplet x64-windows freeimage openblas fftw3
        git clone https://github.com/arrayfire/arrayfire.git
        cd arrayfire && mkdir build
        cd build && cmake -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems" ..
        cmake --build ./ -j4 --config Release
        cmake --install ./
